### ISSUE TITLE
user add: unhandled backend error when e-mail exists

### ISSUE THREAD

**Issue by sphakka** [Zepmann/lldap-cli#10]
When adding a user whose e-mail is already in the DB (possibly for a different user), the resulting backend error is not correctly handled:
```bash
$ lldap-cli user add foobar foo@bar.quux
Created user: foobar
$ lldap-cli user add foobar foo@bar.quux
ERROR: Database error: `Execution Error: error returned from database: (code: 2067) UNIQUE constraint failed: users.email`
$ echo $?
0
```
Indeed, the exit code should be != 0.

**Comment by Zepmann** [comment]
The error is correct (LLDAP uses email addresses as unique values), and it should give a proper exit code. I'll test this in the next week and come up with a fix if needed.
