### ISSUE TITLE
Error in documentation about changing password

### ISSUE THREAD

**Issue by ldidry** [Zepmann/lldap-cli#6]
The documentation says:
```bash
lldap-cli user update john.smith@example.com password hunter2
```
but this will give the help page.

The correct syntax seems to be:
```bash
lldap-cli user update set john.smith@example.com password hunter2
```
(adding a `set` after `update`)

**Comment by Zepmann** [comment]
Will look at this in the coming week.

**Comment by Zepmann** [comment]
Fixed. Thanks for reporting, @ldidry.
