### ISSUE TITLE
adding an attribute to schema

### ISSUE THREAD

**Issue by petrosmm** [Zepmann/lldap-cli#8]
when using lldap-cli it returns the following error message: `Unknown field \addUserAttribute\ on type \Mutation\` when doing command `./lldap-cli schema attribute user add vpnpassword string -v -e`; the env url, admin, password are all setup and i tested with wrong ones to make sure

`./lldap-cli schema attribute user list` yields a  weirder message: `./lldap-cli: line 620: column: command not found`

what could I be doing wrong?

**Comment by Zepmann** [comment]
Which version of lldap are you using?

**Comment by petrosmm** [comment]
@Zepmann `lldap 0.5.0` "current stable"; also thank you for getting back to me quickly...

**Comment by Zepmann** [comment]
As noted in [README.md](https://github.com/Zepmann/lldap-cli/blob/main/README.md):

```
LDAP schema management. Create, delete and use custom user and group attributes and object classes. **Use the latest development version of LLDAP to fully support this feature**.
```
